spring:
  application:
    name: reservas
    datasource:
      url: jdbc:h2:mem:reservasdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
    sql:
      init:
        platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  messages:
    basename: i18n/messages
    encoding: utf-8
    fallback-to-system-locale: false
    use-code-as-default-message: true

joinfaces:
  primefaces:
    theme: saga
  faces:
    project-stage: Production
    facelets-libraries: /tags/tags.taglib.xml